root = "."
tmp_dir = "bin"

[build]
  bin = "./bin/main"
  cmd = "make build"

  delay = 1000
  exclude_dir = ["bin", "public"]
  exclude_file = ["public/styles.css"]
  exclude_regex = ['.*_templ\.go$']
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "templ", "css"]
  include_file = [".env"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false
