services:
  piquel-fr:
    image: ghcr.io/piquelorganization/piquel.fr:${GIT_COMMIT_HASH:-latest}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.piquel-fr.loadbalancer.server.port=${PORT}"
      - "traefik.http.routers.piquel-fr.rule=Host(`${HOST}`)"
      - "traefik.http.routers.piquel-fr.entrypoints=piquel-https"
      - "traefik.http.routers.piquel-fr.tls.certresolver=piquel-resolver"
    environment:
      HOST: 0.0.0.0
      PORT: 80
    deploy:
      update_config:
        order: start-first
    networks:
      - piquel-network

networks:
  piquel-network:
    external: true
    name: piquel-network
