services:
  piquel-fr:
    image: ghcr.io/piquelorganization/piquel.fr:${GIT_COMMIT_HASH:-latest}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.piquel-fr.loadbalancer.server.port=${PORT}"
      - "traefik.http.routers.piquel-fr.rule=Host(`piquel.fr`)"
      - "traefik.http.routers.piquel-fr.entrypoints=websecure"
      - "traefik.http.routers.piquel-fr.tls.certresolver=piquel-resolver"
    environment:
      HOST: ${HOST}
      PORT: ${PORT}
      # Database
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      # Auth
      AUTH_GITHUB_CLIENT_ID: ${AUTH_GITHUB_CLIENT_ID}
      AUTH_GITHUB_CLIENT_SECRET: ${AUTH_GITHUB_CLIENT_SECRET}
      AUTH_GOOGLE_CLIENT_ID: ${AUTH_GOOGLE_CLIENT_ID}
      AUTH_GOOGLE_CLIENT_SECRET: ${AUTH_GOOGLE_CLIENT_SECRET}
      # Cookies
      COOKIES_AUTH_SECRET: ${COOKIES_AUTH_SECRET}
    deploy:
      update_config:
        order: start-first

networks:
  piquel-network:
    external: true
    name: piquel-network
