name: Bug Report
description: Report a bug.
title: "[BUG] "
labels: ["bug"]
projects: ["PiquelOrganization/1"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the bug report as accurately and diligently as possible.
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: What happened? what did you expect to happen? and how can we reproduce this bug?
    validations:
      required: true
  - type: textarea
    id: logs
    label: Logs
    attributes:
      description: If you have access to any logs, please paste them here.
    validations:
      required: false
  - type: checkboxes
    attributes:
      options:
        - label: Would you be willing/able to fix this bug yourself?
          required: true
