name: Build and Deploy
on:
  push:
    branches:
      - "main"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/piquelchips/piquel.fr:latest
            ghcr.io/piquelchips/piquel.fr:${{ github.sha }}
    
  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Stack Deploy
        uses: cssnr/stack-deploy-action@v1
        with:
          name: piquel-fr
          file: docker-stack.yaml
          host: piquel.fr
          user: deploy
          ssh_key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
