name: Build and Deploy
on:
  push:
    branches:
      - "main"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/piquelorganization/piquel.fr:latest
            ghcr.io/piquelorganization/piquel.fr:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
    
  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create env file
        run: |
          echo "DB_HOST=${{ vars.DB_HOST }}" >> ./envfile
          echo "DB_PORT=${{ vars.DB_PORT }}" >> ./envfile
          echo "DB_NAME=${{ vars.DB_NAME }}" >> ./envfile
          echo "DB_USER=${{ secrets.DB_USER }}" >> ./envfile
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> ./envfile
          echo "AUTH_GITHUB_CLIENT_ID=${{ secrets.AUTH_GITHUB_CLIENT_ID }}" >> ./envfile
          echo "AUTH_GITHUB_CLIENT_SECRET=${{ secrets.AUTH_GITHUB_CLIENT_SECRET }}" >> ./envfile
          echo "AUTH_GOOGLE_CLIENT_ID=${{ secrets.AUTH_GOOGLE_CLIENT_ID }}" >> ./envfile
          echo "AUTH_GOOGLE_CLIENT_SECRET=${{ secrets.AUTH_GOOGLE_CLIENT_SECRET }}" >> ./envfile
          echo "COOKIES_AUTH_SECRET=${{ secrets.COOKIES_AUTH_SECRET }}" >> ./envfile
          echo "COOKIES_AUTH_AGE_IN_SECONDS=${{ secrets.COOKIES_AUTH_AGE_IN_SECONDS }}" >> ./envfile
          echo "GIT_COMMIT_HASH=${{ github.sha }}" >> ./envfile

      - name: Docker Stack Deploy
        uses: cssnr/stack-deploy-action@v1
        with:
          name: piquel-fr
          file: docker-stack.yml
          host: piquel.fr
          user: deploy
          ssh_key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          env_file: ./envfile
